//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotizacion_En_Linea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class linxcotiz
    {
        public int id { get; set; }
        public int idLinLicit { get; set; }
        public int cantidad { get; set; }
        public decimal costo { get; set; }
        public int idCotizacion { get; set; }
    
        public virtual cotizaciones cotizaciones { get; set; }
        public virtual linxlicit linxlicit { get; set; }
    }
}
