// <auto-generated />
using System;
using CotizLicitAPI.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CotizLicitAPI.Migrations
{
    [DbContext(typeof(LicitacionContext))]
    [Migration("20210730104955_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CotizLicitAPI.Models.Cotizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LicitacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LicitacionId");

                    b.ToTable("Cotizacion");
                });

            modelBuilder.Entity("CotizLicitAPI.Models.Licitacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Expediente")
                        .IsRequired()
                        .HasColumnType("nvarchar(9)");

                    b.Property<DateTime>("FecApertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FecCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Licitacions");
                });

            modelBuilder.Entity("CotizLicitAPI.Models.LinsxCotiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("CotizacionId")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CotizacionId");

                    b.ToTable("LinsxCotiz");
                });

            modelBuilder.Entity("CotizLicitAPI.Models.LinsxLicit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("LicitacionId")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UnidadMedida")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LicitacionId");

                    b.ToTable("LinsxLicit");
                });

            modelBuilder.Entity("CotizLicitAPI.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FecApertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FecCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Proveedor");
                });

            modelBuilder.Entity("CotizLicitAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DocId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("CotizLicitAPI.Models.Cotizacion", b =>
                {
                    b.HasOne("CotizLicitAPI.Models.Licitacion", null)
                        .WithMany("Cotizaciones")
                        .HasForeignKey("LicitacionId");
                });

            modelBuilder.Entity("CotizLicitAPI.Models.Licitacion", b =>
                {
                    b.HasOne("CotizLicitAPI.Models.Proveedor", null)
                        .WithMany("Licitaciones")
                        .HasForeignKey("ProveedorId");
                });

            modelBuilder.Entity("CotizLicitAPI.Models.LinsxCotiz", b =>
                {
                    b.HasOne("CotizLicitAPI.Models.Cotizacion", null)
                        .WithMany("LineasCotizacion")
                        .HasForeignKey("CotizacionId");
                });

            modelBuilder.Entity("CotizLicitAPI.Models.LinsxLicit", b =>
                {
                    b.HasOne("CotizLicitAPI.Models.Licitacion", null)
                        .WithMany("LineasLicitacion")
                        .HasForeignKey("LicitacionId");
                });

            modelBuilder.Entity("CotizLicitAPI.Models.Usuario", b =>
                {
                    b.HasOne("CotizLicitAPI.Models.Proveedor", null)
                        .WithMany("Usuarios")
                        .HasForeignKey("ProveedorId");
                });

            modelBuilder.Entity("CotizLicitAPI.Models.Cotizacion", b =>
                {
                    b.Navigation("LineasCotizacion");
                });

            modelBuilder.Entity("CotizLicitAPI.Models.Licitacion", b =>
                {
                    b.Navigation("Cotizaciones");

                    b.Navigation("LineasLicitacion");
                });

            modelBuilder.Entity("CotizLicitAPI.Models.Proveedor", b =>
                {
                    b.Navigation("Licitaciones");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
